apiVersion: edna.graitdm.edu/v1
kind: EdnaJob
metadata:
  name: test-job
spec:
  import_key: job1-stream
  export_key: out-topic
  jobname: test-job
  applicationname: kafkasimple
  filename: SimpleKafkaExample
  jobcontext: ednaconf
  jobtype: internal
  jobimagetag: latest
  registryhost: localhost
  registryport: 5000
  jobvariablenames:
    - bootstrap_server
  jobvariablevalues:
    - "edna-cluster-kafka-bootstrap.kafka.svc.cluster.local"
