http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ['localhost']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
